// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

/*
Package users is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	User
*/
package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Name      string   `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Age       int32    `protobuf:"varint,2,opt,name=Age,json=age" json:"Age,omitempty"`
	Documents []string `protobuf:"bytes,3,rep,name=Documents,json=documents" json:"Documents,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetDocuments() []string {
	if m != nil {
		return m.Documents
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "users.User")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d,
	0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xbc, 0xb8, 0x58, 0x42,
	0x8b, 0x53, 0x8b, 0x84, 0x84, 0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x85, 0x04, 0xb8, 0x98, 0x1d, 0xd3, 0x53, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x58, 0x83, 0x98, 0x13, 0xd3, 0x53, 0x85, 0x64, 0xb8, 0x38, 0x5d, 0xf2, 0x93,
	0x4b, 0x73, 0x53, 0xf3, 0x4a, 0x8a, 0x25, 0x98, 0x15, 0x98, 0x35, 0x38, 0x83, 0x38, 0x53, 0x60,
	0x02, 0x49, 0x6c, 0x60, 0x93, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xe9, 0x5f, 0x2e,
	0x68, 0x00, 0x00, 0x00,
}
